-- Crear un esquema: ALMACEN
-- El SCRIPT se ejecuta como SYSTEM

-- Crear el usuario

create user almacen identified by secreto;


-- Privilegio CREATE SESSION para ALMACEN

GRANT CREATE SESSION TO ALMACEN;


-- Asignar recursos al usuario ALMACEN

GRANT RESOURCE TO ALMACEN;


-- Crear la tabla PRODUCTO

CREATE TABLE ALMACEN.PRODUCTO(
  PROD_ID NUMBER(10) PRIMARY KEY,
  PROD_NOMBRE VARCHAR2(100) NOT NULL,
  PROD_PRECIO NUMBER(10,2) NOT NULL,
  PROD_STOCK  NUMBER(10)
);


INSERT INTO ALMACEN.PRODUCTO VALUES(1,'PRODUTCO 1', 1000.0, 500);
INSERT INTO ALMACEN.PRODUCTO VALUES(2,'PRODUTCO 2', 2000.0, 800);
INSERT INTO ALMACEN.PRODUCTO VALUES(3,'PRODUTCO 3', 1500.0, 300);

SELECT * FROM ALMACEN.PRODUCTO;

COMMIT;


-- Tabla VENTA

CREATE TABLE ALMACEN.VENTA(
  VEN_ID NUMBER(10) PRIMARY KEY,
  VEN_FECHA DATE NOT NULL,
  PROD_ID NUMBER(10) NOT NULL,
  VEN_PRECIO NUMBER(10,2) NOT NULL,
  VEN_CANTIDAD NUMBER(10) NOT NULL,
  VEN_IMPORTE NUMBER(10,2) NOT NULL,
  CONSTRAINT FK_VENTA_PRODUCTO
    FOREIGN KEY (PROD_ID) 
    REFERENCES ALMACEN.PRODUCTO
);


INSERT INTO ALMACEN.VENTA VALUES(1,SYSDATE,1,900,4,0);
INSERT INTO ALMACEN.VENTA VALUES(2,SYSDATE,1,890,8,0);
INSERT INTO ALMACEN.VENTA VALUES(3,SYSDATE,1,9450,7,0);
INSERT INTO ALMACEN.VENTA VALUES(4,SYSDATE,2,900,56,0);
INSERT INTO ALMACEN.VENTA VALUES(5,SYSDATE,2,380,23,0);
INSERT INTO ALMACEN.VENTA VALUES(6,SYSDATE,2,690,90,0);
INSERT INTO ALMACEN.VENTA VALUES(7,SYSDATE,3,500,4,0);
INSERT INTO ALMACEN.VENTA VALUES(8,SYSDATE,3,560,9,0);
INSERT INTO ALMACEN.VENTA VALUES(9,SYSDATE,3,860,7,0);

SELECT * FROM ALMACEN.VENTA;

UPDATE ALMACEN.VENTA
SET VEN_IMPORTE = VEN_PRECIO * VEN_CANTIDAD;

COMMIT;



